baseURL = 'https://brainandexperience.org/'
languageCode = 'en-us'
title = 'Brain & Experience Lab'
theme = 'gokarna'

[menu]
  [[menu.main]]
    name = "News"
    url = "/news/"

  [[menu.main]]
    name = "Lab profile"
    url = "/lab-profile/"

  [[menu.main]]
    name = "Publications"
    url = "/publications/"

[params]
  avatarURL = "/images/logo-faceonly.svg"
  customHeadHTML = '<link rel="stylesheet" href="/css/custom-styles.css">'
  accentColor = "#313f76" # dark blue from logo