baseURL = 'https://brainandexperience.org/'
languageCode = 'en-us'
title = 'Brain & Experience Lab'
theme = 'gokarna'

[markup.goldmark.renderer]
unsafe = true

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"

  [[menu.main]]
    name = "Lab profile"
    url = "/lab-profile/"

  [[menu.main]]
    name = "Publications"
    url = "/publications/"

  [[menu.main]]
    name = "People"
    url = "/people/"

[params]
  avatarURL = "/images/logo-faceonly.svg"
  customHeadHTML = '<link rel="stylesheet" href="/css/custom-styles.css">'
  accentColor = "#c94e4eff"