baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'gokarna'

[menu]
  [[menu.main]]
    name = "News"
    url = "/news/"

  [[menu.main]]
    name = "Tags"
    url = "/tags/"

[params]
  avatarURL = "/images/logo-faceonly.svg"
  customHeadHTML = '<link rel="stylesheet" href="/css/custom-styles.css">'